[package]
name = "advent-of-code"
edition = "2024"
description = "My Advent of Code solutions in Rust"
repository = "https://github.com/krobbi/advent-of-code"
publish = false

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
json = "0.12.4"
md5 = "0.8.0"

[lints.rust]
unknown_lints = "forbid"

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
must_use_candidate = "allow"

[profile.release]
strip = true
lto = true
panic = "abort"
codegen-units = 1
